[tool.poetry]
name = "news_topic_classifier"
version = "0.1.0"
description = "A classifier for categorizing news by topic"
authors = ["Julio Lau <julioklau97@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "news_topic_classifier", from = "src" }]

[tool.poetry.dependencies]
python = "^3.12"
python-dateutil = "^2.9.0.post0"
kedro = "^1.0.0"
pandas = "^2.3.1"
kedro-datasets = "^8.0.0"

[tool.poetry.scripts]
news-classifier = "news_topic_classifier.main:main"

[tool.kedro]
project_name = "news_topic_classifier"
package_name = "news_topic_classifier"
kedro_init_version = "1.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.kedro_telemetry]
project_id = "45493260824a4bc0a8f2f7a384346851"
